import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type { FastifyInstance } from 'fastify';
import { buildServer, REQUEST_ID_RE } from './app.js';

// Route-level tests using Fastify's in-memory `inject()` — no real HTTP,
// no port binding, no rate limiter (disabled for the test app). These
// lock in the M2 hardening surface: cache headers, request-id reflection,
// CORS, and the OpenAPI shape.
//
// Note: `/health` does call `prisma.item.count()`, so this suite implicitly
// requires a reachable DB (via `make db-up` + `prisma migrate deploy`).
// /sub-categories is also exercised but doesn't hit the DB — it reads
// from the static TS constants module. Full DB-coverage route tests for
// `/items` (cursor edge cases, search, pagination) live in M7.

describe('app: middleware + headers (DB reachable)', () => {
  let app: FastifyInstance;

  beforeAll(async () => {
    app = await buildServer({ logger: false, disableRateLimit: true });
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
  });

  describe('x-request-id', () => {
    it('generates a UUID when no incoming X-Request-Id is provided', async () => {
      const res = await app.inject({ method: 'GET', url: '/health' });
      const id = res.headers['x-request-id'];
      expect(typeof id).toBe('string');
      // UUID v4 shape — generated by crypto.randomUUID
      expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
    });

    it('reflects a well-formed incoming X-Request-Id', async () => {
      const supplied = 'req-abc-123';
      const res = await app.inject({
        method: 'GET',
        url: '/health',
        headers: { 'x-request-id': supplied },
      });
      expect(res.headers['x-request-id']).toBe(supplied);
    });

    it('rejects (and replaces) malformed X-Request-Id', async () => {
      const evil = 'a'.repeat(500); // length > REQUEST_ID_MAX_LEN
      const res = await app.inject({
        method: 'GET',
        url: '/health',
        headers: { 'x-request-id': evil },
      });
      const id = res.headers['x-request-id'] as string;
      expect(id).not.toBe(evil);
      expect(id.length).toBeLessThanOrEqual(128);
      expect(REQUEST_ID_RE.test(id)).toBe(true);
    });

    it('rejects X-Request-Id with control characters', async () => {
      const evil = "good\nbad";
      const res = await app.inject({
        method: 'GET',
        url: '/health',
        headers: { 'x-request-id': evil },
      });
      expect(res.headers['x-request-id']).not.toBe(evil);
    });
  });

  describe('Cache-Control', () => {
    it('sets long-TTL cache headers on /sub-categories (deterministic)', async () => {
      const res = await app.inject({ method: 'GET', url: '/sub-categories?category=ORG' });
      expect(res.statusCode).toBe(200);
      const cc = res.headers['cache-control'];
      expect(cc).toContain('public');
      expect(cc).toMatch(/max-age=300/);
      expect(cc).toMatch(/s-maxage=3600/);
    });

    it('does NOT set Cache-Control on /health (probes must be live)', async () => {
      const res = await app.inject({ method: 'GET', url: '/health' });
      expect(res.headers['cache-control']).toBeUndefined();
    });
  });

  describe('CORS', () => {
    it('reflects the configured CORS origin on a preflight', async () => {
      const res = await app.inject({
        method: 'OPTIONS',
        url: '/health',
        headers: {
          origin: 'http://localhost:3000',
          'access-control-request-method': 'GET',
        },
      });
      expect(res.headers['access-control-allow-origin']).toBe('http://localhost:3000');
    });
  });

  describe('OpenAPI', () => {
    it('serves /docs/json with the expected paths and tags', async () => {
      const res = await app.inject({ method: 'GET', url: '/docs/json' });
      expect(res.statusCode).toBe(200);
      const spec = res.json() as {
        paths: Record<string, unknown>;
        info: { title: string };
      };
      expect(spec.info.title).toBe('Jopay Donation API');
      expect(Object.keys(spec.paths).sort()).toEqual([
        '/health',
        '/items',
        '/items/{id}',
        '/sub-categories',
      ]);
    });

    it('serves the Swagger UI HTML at /docs', async () => {
      const res = await app.inject({ method: 'GET', url: '/docs' });
      // /docs redirects to /docs/static/index.html or returns HTML directly
      expect([200, 301, 302]).toContain(res.statusCode);
    });
  });
});
