/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + DB connectivity probe
         * @description Validates connectivity by counting items via Prisma (Hard Rule 3 — no raw SQL). Excluded from rate limiting. Probes intentionally do not set `Cache-Control` so dependents always see fresh state.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            dbConnected: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items with cursor pagination, filters, and search
         * @description Returns `{ items, nextCursor }`. Sets `Cache-Control: public, max-age=30, s-maxage=60` on 200 responses. Every response carries an `x-request-id` header for log correlation.
         */
        get: {
            parameters: {
                query: {
                    /** @description Tab category — required */
                    category: "ORG" | "CAMPAIGN" | "MERCHANDISE";
                    /** @description Sub-category filter (must be valid for the chosen category) */
                    subCategory?: string;
                    /** @description Case-insensitive substring match on title and description */
                    q?: string;
                    /** @description Opaque cursor returned by a previous list response */
                    cursor?: string;
                    /** @description Page size (default 20, max 100) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                /** @enum {string} */
                                category: "ORG" | "CAMPAIGN" | "MERCHANDISE";
                                subCategory: string;
                                title: string;
                                description: string;
                                logoUrl: string;
                                /** Format: date-time */
                                createdAt: string;
                                amountRaised: number | null;
                                amountGoal: number | null;
                                /** Format: date-time */
                                deadline: string | null;
                                price: number | null;
                                stock: number | null;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single item by id
         * @description Returns the full item or 404. Sets `Cache-Control: public, max-age=60, s-maxage=300` on 200 responses. Every response carries an `x-request-id` header for log correlation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            /** @enum {string} */
                            category: "ORG" | "CAMPAIGN" | "MERCHANDISE";
                            subCategory: string;
                            title: string;
                            description: string;
                            logoUrl: string;
                            /** Format: date-time */
                            createdAt: string;
                            amountRaised: number | null;
                            amountGoal: number | null;
                            /** Format: date-time */
                            deadline: string | null;
                            price: number | null;
                            stock: number | null;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sub-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sub-categories for a given category (drives the 全部 dropdown)
         * @description Sub-categories are derived from a static TS constant — they don't change between deploys. Sets aggressive `Cache-Control: public, max-age=300, s-maxage=3600`. Every response carries an `x-request-id` header for log correlation.
         */
        get: {
            parameters: {
                query: {
                    /** @description Category whose sub-categories to list */
                    category: "ORG" | "CAMPAIGN" | "MERCHANDISE";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            value: string;
                            label: string;
                        }[];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
